### ISSUE TITLE
template parameter file

### ISSUE THREAD

**Issue by codebreaker2** [dbosul/KiLLER#3]
I'm a bit confused about the syntax for the parameter file. 
I'm trying to crop frames:

$ python /Users/cmartin/Software/kcwi/cwitools/cwitools/scripts/cwi_crop.py -params j1044.param -cubetype icubes.fits

Here is the parameter file. The '.txt' was added so that github would upload it. Previously image sections were specified with a ":", but the help file says to use a ",".  I tried it both ways and got the same error message.

[j1044.param.txt](https://github.com/dbosul/cwitools/files/4332100/j1044.param.txt)

$ python /Users/cmartin/Software/kcwi/cwitools/cwitools/scripts/cwi_crop.py -params j1044.param -cubetype icubes.fits
Traceback (most recent call last):
  File "/Users/cmartin/Software/kcwi/cwitools/cwitools/scripts/cwi_crop.py", line 127, in <module>
    if __name__=="__main__": main()
  File "/Users/cmartin/Software/kcwi/cwitools/cwitools/scripts/cwi_crop.py", line 74, in main
    if os.path.isfile(args.params): params = parameters.load_params(args.params)
  File "/Users/cmartin/Software/kcwi/CWITools/cwitools/parameters.py", line 46, in load_params
    key, val = line.split('=')
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by dbosul** [comment]
Hi,

I cut down the parameter files in v0.5 to get rid of the big table, which makes it a bit simpler to initialize them. (New syntax example here 
https://github.com/dbosul/cwitools/blob/v0.5/cwitools/template.param
)

Rather than having the crop parameters in the parameter file, they are now given as arguments when calling cwi_crop:

`python cwitools/scripts/cwi_crop.py -params j1044.param -cubetype icubes.fits -xcrop 1:24 -ycrop 15:70 -wcrop 4400:4500 `

or you can use the -auto flag to determine them automatically (but should inspect the results)

`python cwitools/scripts/cwi_crop.py -params j1044.param -cubetype icubes.fits -auto`

The `-plot` flag should let you see how the cropping for each axis looks so you can determine the best parameters.

This was done because usually (as in your param file) the crop parameters are the same for each cube, so it was a bit redundant to keep the table format, and made it more awkward to create parameter files. If you have a preference on how this should be done - let me know and I'll see if I can incorporate it into v0.6.

Thanks,
Donal

**Comment by codebreaker2** [comment]
I am having trouble with the Crop code just hanging, returning neither the prompt nor an error message.

$ python /Users/cmartin/Software/kcwi/cwitools/cwitools/scripts/cwi_crop.py -params j1044.param -cubetype icubes.fits -plot -xcrop 12:37 -ycrop 27:167 -wcrop 3490:5610

Once it returned the first of the three plots:
![Figure_1](https://user-images.githubusercontent.com/47435481/77377859-ae1a3680-6d31-11ea-921e-642574817d5c.png)

[j1044.param.txt](https://github.com/dbosul/cwitools/files/4372602/j1044.param.txt)

**Comment by dbosul** [comment]
Hi,

I think this is a operating-system dependent bug - could you let me know what OS you are running? I have experienced something similar on Ubuntu, and I suspect it may be the same cause. 

Thanks!
Donal

**Comment by dbosul** [comment]
Also let me know which environment you are using to run the code (e.g. running as a terminal command, or in an iPython notebook, etc.)

**Comment by dbosul** [comment]
Moving this to new issue  - to separate parameter file and matplotlib issue.

**Comment by codebreaker2** [comment]
Hi Donal,

 

I am running macOS Sierra 10.12.6. 

I am running CWITools from the command line. 

I am in a python 3.7 Astroconda environment.

 
On my first execution of the following command, the plot that shows the cropping pops up.  My impression is that this plot is for the first frame.  I do not get plots for the other two frames. The terminal window hangs as shown below.  (If I close the plot window with the red button, the terminal remains hung.)
 

$ python /Users/cmartin/Software/kcwi/cwitools/cwitools/scripts/cwi_crop.py -params j1044.param -cubetype icubes.fits -plot -auto

 

 

AutoCrop Parameters:

     x-crop: 09:34

     y-crop: 24:170

     z-crop: 633:4598 (3644:5626 A)

 

 
I ran the same command again, and I hit ‘return’ in the plot window. I got all three plots.  And CWITools wrote the *.c.fits files☺   So, very good, but I do not understand why it suddenly worked.
I repeated (2), and I did not get the same response. The plot window would not close when I hit return. The code remained hung. It looks like the first of the three *.c.fits files was overwritten, but the other two files were not written.
I deleted the *c.fits files. Then repeated (2).  Same response as in (1) and (3).  So although it worked once in (2), I can not repeat the behavior.
 

Next, I tried changing the matplotlib backend, per your suggestion. My file structure is similar to yours:

 

print(matplotlib.matplotlib_fname())

 

       /Users/cmartin/Software/anaconda/envs/astroconda37/lib/python3.7/site-packages/matplotlib/mpl-data/matplotlibrc

 

I note the following comment, which makes it sound like MacOSX is already selected as the default.

## The default backend. If you omit this parameter, the first

## working backend from the following list is used:

## MacOSX Qt5Agg Qt4Agg Gtk3Agg GTK3Cairo TkAgg WxAgg Agg Cairo

Nonetheless, I added this 

#backend      : Agg

backend      : MacOSX

 

opened a new terminal window.  I repeated (2) from above. I attach a copy of the error message; I think it says you can’t add a backend to astroconda python this way.  But, it also seems like the backend is unlikely the problem, as ‘MacOSX’ is the default.

 

 

Any thoughts?

 

Thanks,

Crystal

 

 

p.s. Thesis writing, eh, so it sounds like are graduating this quarter.  What are your plans for fall?

**Comment by dbosul** [comment]
Hi Crystal,

It is good that it worked once - means the backend is working and it's not
an OS issue.

I double checked the code and the plot in reduction.crop() waits for input
via an "*input("")*" command - so, I think the issue might be 'where' the
cursor is when you hit return. If you click on the terminal where you
executed the script, and hit return while in the terminal, that should
close the plot and move on to the next one.

If you hit return while focused on the plot, it may not register and thus
leave the plot hanging.

I will update plots in a future version to use a different closing method,
because I think the issue with input("") is that it does not depend on the
plot itself.

I am defending in July - trying to get a CWITools paper and a second survey
paper together, so a lot of writing! Looking mostly towards industry or
government labs, working on instrumentation ideally!

Thanks,
Donal

**Comment by codebreaker2** [comment]
Hi Donal,

 

Excellent.  It’s that simple.  (I sure thought I had tried clicking in the terminal window previously, but I must not have done it for all three plots.  Or I might have trying hitting ‘q’ instead of return.)

Anyway, this issue is closed. Thank You.

 

The spatial section of the cube that has data depends on wavelength.   So here’s a related question about the cropping strategy. Do we want (1) the union of all the ‘good’ spatial regions, the maximum size for the cropped cube, or (2) the intersection of the ‘good’ spatial regions, the minimum size for the cropped cube.  

 

I prefer keeping all information, (1). But does the coadd routine knows how to deal with a wavelength slice that has no valid data along edge rows and columns?

 

Good luck with the writing.  

 

Crystal

**Comment by dbosul** [comment]
Glad to hear it worked!

Regarding cropping - I typically crop individual cubes to the "WAVGOOD"
region - within which the spatial information should be complete for all
slices (i.e. there should be no slices which have wavelength-dependent
completeness within this range) and then crop the empty rows/columns as a
first pass, sometimes cropping additional rows/columns if there are edge
artifacts.

The coadd routine as of yet does not distinguish between empty input pixels
and non-empty pixels, although it automatically removes empty rows, columns
and wavelength layers at the end. So if you provide input with empty
regions, it will consider that to be a flux measurement.

So for now I recommend cropping empty data, but this gives me an idea that
- for the next release - I can tell the coadd script to ignore NaN input
values, so that a user can set some regions of a cube to NaN to exclude
them from contributing to a coadd.

Thanks!
Donal

**Comment by codebreaker2** [comment]
Hi Donal,

 

Hey, I thought I understood the coadding.  I was successful with another galaxy.  Then I  moved on to a new target, and I’m not getting it.

Apparently I don’t understand the expthresh and pixthresh options well enough. 

 

I have three short (6 sec) exposures of a very compact nucleus. They have positions ‘centered’, ‘left’, and ‘right’. There is a ~2 slice gap between ‘left’ and ‘right’.

 The attached figure, ‘n2_panels_6s’, shows the offsets.  So I thought that in order to include the slice in the gap, I needed to set “-expthresh” to the minimum exposure (6 s) divided by the maximum exposure at any location, which is 2 x 6 s.  So I set “-expthresh 0.49”.

 

Yet, the coadd largely cuts out this central slice.  See coadd.jpeg.

 

An example of how to set the cwi_coadd parameters would be very useful here.  

If you have time to try it, you can download the kb*fits frames here:  http://web.physics.ucsb.edu/~cmartin/data/ .

 

Thanks,

Crystal

**Comment by dbosul** [comment]
Hi Crystal,

That is the correct use of expthresh - so the issue must be something else.
I would recommend just using a conservatively low expthresh and seeing what
the result is (e.g. 0.1)

I do not see an attached image, and unfortunately I don't have much time to
look at coadding the data myself.

Also - please open a new issue or just send me an email in a separate
thread for any new issues, as these emails keep getting posted under the
old parameter file issue you posted on Github.

Thanks,
Donal
